### ISSUE TITLE
LANGUAGE not respected

### ISSUE THREAD

**Issue by nurtext** [daledavies/jump#104]
Hi,

I've tried setting the env var `LANGUAGE` to `de` and restarted the docke container, but nothing happens. The displayed language is still `en`. I also tried with various other values (as listed in https://github.com/daledavies/jump/tree/main/jumpapp/translations) but no luck so far. 

Config as follows:

```yaml
version: '3'

services:
  jump:
    image: daledavies/jump:v1.3.2
    container_name: jump
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /mnt/data/jump/backgrounds:/backgrounds
      - /mnt/data/jump/favicon:/favicon
      - /mnt/data/jump/search:/search
      - /mnt/data/jump/sites:/sites
    environment:
      LANGUAGE: 'de'
```

Debug from within container:

```bash
$ docker compose exec jump sh
$ env | grep -i lang
LANGUAGE=de
```

Is there anything that I'm missing or isn't it working properly?
