### ISSUE TITLE
Time keeps fluctuating

### ISSUE THREAD

**Issue by quaintdev** [daledavies/jump#16]
I saw a weird behavior with my setup. The time on startpage keeps changing by 12 hours and sometimes NaN. This changes greetings from Good Morning to Good Night and then Good undefined. I am using arm image by @Just5KY. Both time on my system and server are properly set. Also I see half hour delay with the time when it is close to my actual time.

![image](https://user-images.githubusercontent.com/59229571/158931956-f7ae1a27-77a9-40eb-9402-7266805c21df.png)

**Comment by Just5KY** [comment]
That's weird.
Did to put in the environment variable for location.

I didn't do it in my testing
Its 9 am right now my time it says 3 am.
I will try setting the env. later to test this

![Uploading t2{8dee363} (473bb17b-e9fe-4298-ae57-d562f2ebcbf0 id=0x7f0a03ac tag=BaseCommentFragment) …]()

**Comment by quaintdev** [comment]
Yes I have set `SITENAME`, `OWMAPIKEY`, `LATLONG` environment variables.

**Comment by Just5KY** [comment]
Ok 
I will add `OWMAPIKEY`, `LATLONG` in my compose and test it

**Comment by Just5KY** [comment]
### Yup, happening to me too.

![image](https://user-images.githubusercontent.com/71321862/158935210-7393cf3b-556d-498c-9e53-00d3db9c78c4.png)

```yml
  jump:
    image: justsky/jump
    container_name: jump
    restart: unless-stopped
    ports:
      - 8321:8080
    volumes:
      - $DOCKERDIR/jump/backgrounds:/backgrounds
      - $DOCKERDIR/jump/sites:/sites
    environment:
      SITENAME: 'SkyPi'
      OWMAPIKEY: 
      LATLONG: 
      CACHEBYPASS: 'true'
      TZ: $TZ 
```
### I even tried adding Timezone env
