### ISSUE TITLE
Feature Request: custom web-root

### ISSUE THREAD

**Issue by gotschi** [daledavies/jump#35]
I use a reverse proxy in my DMZ to forward pages from my internal net to WWW.

If I want to put this page onto domain.tld/start and have it proxy to jump:8123/ it requests the underlying sources wrong with "/" being the webroot.
So instead of `domain.tld/start/background.php` it requests `domain.tld/background.php`

Which of course fails

**Comment by daledavies** [comment]
Interesting, thanks for letting me know. I'll see if I can recreate your reverse proxy scenario and think about possible ways to address this. Possibly an optional `subdirectory` or `wwwroot` config option.

**Comment by gotschi** [comment]
That is usually the case, that apps get proxied per subdomain.
In which case this is not needed.

(I'm also using a wildcard cert which exposes all eventual other subdomains, 
so I like to keep that at 1 domain because it's easier to surveil attacks etc..)

anyways, great landing page I really like the simplicity!

**Comment by daledavies** [comment]
I've added an option for this in v1.2.2 (released today). You can now configure a custom URL via the `WWWURL` environment variable (if using Docker) or the `wwwurl` parameter in `config.php`.

Thank you again for reaching out :)

**Comment by gotschi** [comment]
awesome, thank you!

however, i tried to pull :latest from docker-hub and also :v1.2.2 but it seems I cant get the current one - maybe the CDNs need some time.

anyways thank you for taking care of it!!

**Comment by gotschi** [comment]
Seems like the wwwroot parameter is still missing in L40 classes/Background.php
and also in the static compiled JS assets/js/src/classes/Weather.js

**Comment by gotschi** [comment]
so I used following docker-compose and mapped the repo to /var/www/html

```yaml
        volumes:
            - ./jump/jumpapp:/var/www/html
            - ./backgrounds:/backgrounds
            - ./search:/search
            - ./sites:/sites
        environment:
            SITENAME: '#home'
            OWMAPIKEY: '107c6e8e61f6ba0158f8c6c22a5c8ef9'
            LATLONG: '47.259659,11.400375'
            NOINDEX: 'true'
            SHOWGREETING: 'false'
            WWWURL: '/start'
            CACHEBYPASS: 'true'
```
and I can't get it to work, even with /start manually put in config background and weaterdata.php fail to load (because the js is not compiled?)

anyway I also tried building the container but have no display on my machine :/
`error: failed to solve: failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY``

I never did multiarch builds before

so I'm not much of a help here,
In case for apache however it's a simple vhost <Location> entry to get such pages on a custom slug, I guess nginx is even easier:
```
	<Location /jump>
		ProxyPass http://127.0.0.1:9090/
		ProxyPassReverse http://127.0.0.1:9090/
        </Location>
```
