### ISSUE TITLE
Request WeatherAPI

### ISSUE THREAD

**Issue by daledavies** [daledavies/jump#64]
### Discussed in https://github.com/daledavies/jump/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **Tataukee** October  3, 2022</sup>
Can you add weatherapi ? The openweather has never been working for me ?</div>

**Comment by daledavies** [comment]
And this works without the API key? The errors in your logs seem unrelated to problems with the weather API.

I'm reading this on my phone so can't quite see it properly but it looks like the site status function is caching a URL that is at the end of a redirect from one of your site's, it is complaining about the filename of the cache file created. This might be a bug but it isn't in any way related to the weather API.

Could you try with the API key in place and the `CACHEBYPASS` option set to `true`?

**Comment by Tataukee** [comment]
This is the only logs I could see unfortunately and the issue is happening from different browsers and different machines in my LAN including from my other iDevice, however when removing the OWAPI key the page just works .
This is by the way docker running in Synology and my browser is Safari I do not have any special setup or caching issues when running other containers . Tried both variables none of them seems resolving the issue .
I have the OWAPI Key working in other project , tested this morning and it's working . The app is launched from the same browser with the same machine and showing my weather correctly .


![04Oct2207-48](https://user-images.githubusercontent.com/26170999/193744684-829f05e8-3f89-43d7-942c-74bd0426a7e9.png)

**Comment by daledavies** [comment]
Thanks, can you test as I asked above with cachebypass and then checkstatus?

**Comment by Tataukee** [comment]
Just to confirm with you, those variables do you want me to include them on the docker compose environnement .
something like this in the screenshot ? 

![04Oct2207-59](https://user-images.githubusercontent.com/26170999/193745594-f1ed7a6c-ebc1-42af-9284-9511a52d02bc.png)

**Comment by Tataukee** [comment]
p/s: I have done one by one by the way , following your instructions

**Comment by daledavies** [comment]
Yes as docker environment variables, thanks

**Comment by Tataukee** [comment]
None of the above seems to work . ( tried different browsers )

**Comment by daledavies** [comment]
Can you forward the logs with each of these in place?

**Comment by Tataukee** [comment]
CACHEBYPASS = true **logs** :

-------------------------------------------------------------

     ██ ██    ██ ███    ███ ██████
     ██ ██    ██ ████  ████ ██   ██
     ██ ██    ██ ██ ████ ██ ██████
██   ██ ██    ██ ██  ██  ██ ██
 █████   ██████  ██      ██ ██

https://github.com/daledavies/jump

-------------------------------------------------------------

- Repopulating web root with application files.
- You are using Jump v1.3.0 (1658838937)

-------------------------------------------------------------

- Checking if backgrounds, favicon, search or sites volumes have been mounted.
   - Backgrounds directory is mapped... symlinking.
   - Favicon directory is mapped... symlinking.
   - Sites directory is mapped... symlinking.
   - Search directory is mapped... symlinking.

- All done! Starting nginx/php services now.

-------------------------------------------------------------

[04-Oct-2022 06:28:03] NOTICE: fpm is running, pid 23
[04-Oct-2022 06:28:03] NOTICE: ready to handle connections
172.19.0.1 - - [04/Oct/2022:06:28:22 +0000] "GET /api/weather/1140c11dc9db2c37a8c9f46b275b0f25878d2ea667533831c531e5c9ebc68eeb/ HTTP/1.1" 401 47 "http://10.0.1.18:8122/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" "-" 0.041 0.041 . -
172.19.0.1 - - [04/Oct/2022:06:29:34 +0000] "GET /tag/devOP/ HTTP/1.1" 200 5157 "http://10.0.1.18:8122/tag/media%20server/?nocache=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.059 0.059 . -
172.19.0.1 - - [04/Oct/2022:06:29:34 +0000] "GET /background-css.php HTTP/1.1" 200 143 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.004 0.004 . -
172.19.0.1 - - [04/Oct/2022:06:29:34 +0000] "GET /api/status// HTTP/1.1" 401 47 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.003 0.003 . -
172.19.0.1 - - [04/Oct/2022:06:29:34 +0000] "GET /assets/font/quicksand-v28-latin-regular.woff2 HTTP/1.1" 200 13776 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.000 - . -
172.19.0.1 - - [04/Oct/2022:06:29:34 +0000] "GET /api/weather// HTTP/1.1" 401 47 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.002 0.002 . -
172.19.0.1 - - [04/Oct/2022:06:29:34 +0000] "GET /assets/backgrounds/documerica-6FLfd2_OxBM-unsplash.jpg HTTP/1.1" 200 488175 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.010 - . -


CHECKSTATUS = false **logs** :

-------------------------------------------------------------

     ██ ██    ██ ███    ███ ██████
     ██ ██    ██ ████  ████ ██   ██
     ██ ██    ██ ██ ████ ██ ██████
██   ██ ██    ██ ██  ██  ██ ██
 █████   ██████  ██      ██ ██

https://github.com/daledavies/jump

-------------------------------------------------------------

- Repopulating web root with application files.
- You are using Jump v1.3.0 (1658838937)

-------------------------------------------------------------

- Checking if backgrounds, favicon, search or sites volumes have been mounted.
   - Backgrounds directory is mapped... symlinking.
   - Favicon directory is mapped... symlinking.
   - Sites directory is mapped... symlinking.
   - Search directory is mapped... symlinking.

- All done! Starting nginx/php services now.

-------------------------------------------------------------

[04-Oct-2022 06:34:23] NOTICE: fpm is running, pid 22
[04-Oct-2022 06:34:23] NOTICE: ready to handle connections
172.19.0.1 - - [04/Oct/2022:06:34:49 +0000] "GET /tag/devOP/ HTTP/1.1" 200 5157 "http://10.0.1.18:8122/tag/media%20server/?nocache=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.074 0.074 . -
172.19.0.1 - - [04/Oct/2022:06:34:50 +0000] "GET /background-css.php HTTP/1.1" 200 143 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.008 0.008 . -
172.19.0.1 - - [04/Oct/2022:06:34:50 +0000] "GET /api/weather// HTTP/1.1" 401 47 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.003 0.003 . -
172.19.0.1 - - [04/Oct/2022:06:34:50 +0000] "GET /assets/backgrounds/hector-falcon-ZJ9POJfmfL4-unsplash.jpg HTTP/1.1" 200 519961 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.013 - . -
172.19.0.1 - - [04/Oct/2022:06:34:50 +0000] "GET /assets/font/quicksand-v28-latin-regular.woff2 HTTP/1.1" 200 13776 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.000 - . -
172.19.0.1 - - [04/Oct/2022:06:35:10 +0000] "GET /tag/devOP/ HTTP/1.1" 200 5212 "http://10.0.1.18:8122/tag/media%20server/?nocache=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.028 0.029 . -
172.19.0.1 - - [04/Oct/2022:06:35:10 +0000] "GET /background-css.php HTTP/1.1" 200 130 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.001 0.001 . -
172.19.0.1 - - [04/Oct/2022:06:35:10 +0000] "GET /api/weather/2ce3dc9af36a84e362239e61c52f1cb9f7199e98300e139c8ba7d202d9f979d1/ HTTP/1.1" 400 22 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.003 0.004 . -
172.19.0.1 - - [04/Oct/2022:06:35:10 +0000] "GET /assets/font/quicksand-v28-latin-regular.woff2 HTTP/1.1" 304 0 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.000 - . -
172.19.0.1 - - [04/Oct/2022:06:35:10 +0000] "GET /assets/backgrounds/sea-ga4cb2ef0b_1920.jpg HTTP/1.1" 200 865460 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.000 - . -
172.19.0.1 - - [04/Oct/2022:06:36:36 +0000] "GET /tag/devOP/ HTTP/1.1" 200 5212 "http://10.0.1.18:8122/tag/media%20server/?nocache=1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.024 0.024 . -
172.19.0.1 - - [04/Oct/2022:06:36:36 +0000] "GET /background-css.php HTTP/1.1" 200 146 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.001 0.001 . -
172.19.0.1 - - [04/Oct/2022:06:36:36 +0000] "GET /api/weather/2ce3dc9af36a84e362239e61c52f1cb9f7199e98300e139c8ba7d202d9f979d1/ HTTP/1.1" 400 22 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.003 0.003 . -
172.19.0.1 - - [04/Oct/2022:06:36:36 +0000] "GET /assets/font/quicksand-v28-latin-regular.woff2 HTTP/1.1" 304 0 "http://10.0.1.18:8122/tag/devOP/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" "-" 0.000 - . -

**Comment by Tataukee** [comment]
Hi There , Any feedback on this ?

**Comment by daledavies** [comment]
The most recent error logs you forwarded don't actually show any errors, I'm afraid there isn't much for me to work with.

If you manage to capture any errors in the console or the docker error logs please forward them with detail of the configuration options in place at the time.

**Comment by Kye-NG** [comment]
I was having the same 400 response issue from the weather API too.

I added a container name to the docker compose block, and also changed the environment variables mappings from the example to suite what my other docker image blocks looked like:

From:
```
landing-page:
  image: daledavies/jump
  ports:
    - 8123:8080
  volumes:
    - /opt/jump/backgrounds:/backgrounds
    - /opt/jump/favicon:/favicon
    - /opt/jump/search:/search
    - /opt/jump/sites:/sites
  environment:
    - SITENAME: 'Home'
    - OWMAPIKEY: 'myApiKeyWasHere'
    - LATLONG: '-34.083260,150.689774'
    - AMPMCLOCK: 'true'
    - SHOWSEARCH: 'false'
    - ALTBGPROVIDER: 'https://source.unsplash.com/random'
    - METRICTEMP: 'true'
    - CHECKSTATUS: 'false'
   ```

To:
``` 
landing-page:
    container_name: landing-page
    image: daledavies/jump
    ports:
      - 8462:8080
    volumes:
      - /opt/jump/backgrounds:/backgrounds
      - /opt/jump/favicon:/favicon
      - /opt/jump/search:/search
      - /opt/jump/sites:/sites
    environment:
      - SITENAME=Home
      - OWMAPIKEY=c249362bbe942c167cf2834a1920ea8a
      - LATLONG=-34.083260,150.689774
      - AMPMCLOCK=true
      - SHOWSEARCH=false
      - ALTBGPROVIDER=https://source.unsplash.com/random
      - METRICTEMP=true
      - CHECKSTATUS=false
```

Weather API works fine now 🤷

**Comment by Kye-NG** [comment]
I was having the same 400 response issue from the weather API too.

I added a container name to the docker compose block, and also changed the environment variables mappings from the example to suite what my other docker image blocks looked like:

From:
```
landing-page:
  image: daledavies/jump
  ports:
    - 8123:8080
  volumes:
    - /opt/jump/backgrounds:/backgrounds
    - /opt/jump/favicon:/favicon
    - /opt/jump/search:/search
    - /opt/jump/sites:/sites
  environment:
    - SITENAME: 'Home'
    - OWMAPIKEY: 'myApiKeyWasHere'
    - LATLONG: 'mylat,mylong'
    - AMPMCLOCK: 'true'
    - SHOWSEARCH: 'false'
    - ALTBGPROVIDER: 'https://source.unsplash.com/random'
    - METRICTEMP: 'true'
    - CHECKSTATUS: 'false'
   ```

To:
``` 
landing-page:
    container_name: landing-page
    image: daledavies/jump
    ports:
      - 8462:8080
    volumes:
      - /opt/jump/backgrounds:/backgrounds
      - /opt/jump/favicon:/favicon
      - /opt/jump/search:/search
      - /opt/jump/sites:/sites
    environment:
      - SITENAME=Home
      - OWMAPIKEY=myApiKeyWasHere
      - LATLONG=mylat,mylong
      - AMPMCLOCK=true
      - SHOWSEARCH=false
      - ALTBGPROVIDER=https://source.unsplash.com/random
      - METRICTEMP=true
      - CHECKSTATUS=false
```

Weather API works fine now 🤷
